export interface Framework {
  id: string
  name: string
  publisher: string
  kind: "Baseline" | "Benchmark" | "Control framework" | "Custom"
  description: string
  source: string
  coverage: string
  disabledReason?: string
  nativeId?: string
  licenseNotice?: string
  /** Assessment and exports only: the pack cannot be used to create policies in a tenant. */
  comparisonOnly?: true
}

/** The UK NCSC Device Security Guidance configuration packs commit (2026-03-04) TenuVault loads and verifies. */
export const NCSC_COMMIT = "681e07584d3f7a84549ff26bda83e4f1480703f6"
export const NCSC_REPOSITORY = "https://github.com/ukncsc/Device-Security-Guidance-Configuration-Packs"

/** Remove from the CIS entries only after the commercial-use contract is signed. */
const CIS_DISABLED_REASON = "CIS comparisons are coming soon."

/** Navigation and assessment capabilities are independent of the pack provider. OpenIntuneBaseline has its own section. */
export const frameworks: Framework[] = [
  { id: "microsoft", name: "Microsoft Security Baselines", publisher: "Microsoft", kind: "Baseline", source: "https://learn.microsoft.com/en-us/intune/device-security/security-baselines/overview", description: "Microsoft security configuration recommendations.", coverage: "Import Settings Catalog policies from your selected baseline and version. Legacy baseline templates are not assessed." },
  { id: "ncsc-dsg", name: "UK NCSC Device Security Guidance", publisher: "UK National Cyber Security Centre", kind: "Baseline", source: NCSC_REPOSITORY, description: "NCSC recommended device configuration packs for Windows endpoints.", coverage: "Load the NCSC 2025 Windows Settings Catalog pack (9 policies) and compare it with your tenant's Settings Catalog policies. The Windows endpoint security and DFCI exports and AppLocker XML are not in a supported format and are not assessed. Apple, Android and ChromeOS guidance is not in Intune policy format and is not assessed.", licenseNotice: "Contains NCSC configuration packs, Crown Copyright, licensed under the Apache License 2.0. Modified for comparison. No endorsement by NCSC.", comparisonOnly: true },
  { id: "cis-benchmarks", name: "CIS Benchmarks", publisher: "Center for Internet Security", kind: "Benchmark", source: "https://www.cisecurity.org/benchmark/intune", description: "Product-specific configuration benchmarks and profiles.", coverage: "Import your licensed Intune policy mappings. Benchmark text and CIS Build Kits are not bundled. Record the benchmark version and Level 1 or Level 2 profile.", disabledReason: CIS_DISABLED_REASON },
  { id: "cis-controls", name: "CIS Controls", publisher: "Center for Internet Security", kind: "Control framework", source: "https://www.cisecurity.org/controls", description: "Prioritized safeguards for an organizational security program.", coverage: "Requires organization-specific mappings and evidence beyond Intune. Imported policies assess only the configuration portion of your selected safeguards.", disabledReason: CIS_DISABLED_REASON },
  { id: "nist-csf", name: "NIST CSF 2.0", publisher: "NIST", kind: "Control framework", source: "https://www.nist.gov/cyberframework", description: "Cybersecurity Framework outcomes for managing organizational risk.", coverage: "Native comparison of selected technical requirements. Organizational controls and actual device enforcement are outside scope.", nativeId: "nist-csf-2", licenseNotice: "NIST-authored publications: royalty-free reuse with attribution; third-party material excluded." },
  { id: "nist-800-53", name: "NIST SP 800-53 Rev. 5", publisher: "NIST", kind: "Control framework", source: "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final", description: "Security and privacy controls for information systems and organizations.", coverage: "Native comparison of selected technical requirements. Organizational controls and actual device enforcement are outside scope.", nativeId: "nist-800-53-r5", licenseNotice: "NIST-authored publications: royalty-free reuse with attribution; third-party material excluded." },
  { id: "nist-800-171", name: "NIST SP 800-171 Rev. 3", publisher: "NIST", kind: "Control framework", source: "https://csrc.nist.gov/pubs/sp/800/171/r3/final", description: "Requirements for protecting controlled unclassified information.", coverage: "Native comparison of selected technical requirements. Organizational controls and actual device enforcement are outside scope.", nativeId: "nist-800-171-r3", licenseNotice: "NIST-authored publications: royalty-free reuse with attribution; third-party material excluded." },
  { id: "stig", name: "DISA STIG", publisher: "DISA", kind: "Benchmark", source: "https://www.cyber.mil/stigs/", description: "Security Technical Implementation Guides for specific products.", coverage: "Import reviewed Settings Catalog mappings for a specific STIG, version and release. Manual checks and device audit findings are not assessed." },
  { id: "essential-eight", name: "ASD Essential Eight", publisher: "Australian Signals Directorate", kind: "Control framework", source: "https://www.cyber.gov.au/business-government/asds-cyber-security-frameworks/essential-eight/essential-eight-maturity-model", description: "Mitigation strategies organized by maturity level.", coverage: "Native comparison of selected technical requirements. Organizational controls and actual device enforcement are outside scope.", nativeId: "essential-eight", licenseNotice: "ASD material: © Commonwealth of Australia 2026, CC BY 4.0. Adapted mapping. No endorsement." },
  { id: "bsi", name: "BSI IT-Grundschutz", publisher: "BSI", kind: "Control framework", source: "https://www.bsi.bund.de/EN/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/it-grundschutz_node.html", description: "Modules and requirements for organizational information security.", coverage: "Native comparison of selected technical requirements. Organizational controls and actual device enforcement are outside scope.", nativeId: "bsi-it-grundschutz", licenseNotice: "Independent mapping. Publisher requirement text and logos are not bundled. No affiliation or certification." },
  { id: "nist-800-171-r2", name: "NIST SP 800-171 Rev. 2", publisher: "NIST", kind: "Control framework", source: "https://csrc.nist.gov/pubs/sp/800/171/r2/upd1/final", description: "Independent Intune configuration comparisons for selected technical requirements.", coverage: "Versioned technical subset with explicit scope and comparison evidence. No audit, certification or full-framework compliance score.", nativeId: "nist-800-171-r2", licenseNotice: "NIST-authored publications: royalty-free reuse with attribution; third-party material excluded." },
  { id: "iso-27001", name: "ISO/IEC 27001:2022", publisher: "International Organization for Standardization / IEC", kind: "Control framework", source: "https://www.iso.org/standard/27001", description: "Independent Intune configuration comparisons for selected technical requirements.", coverage: "Versioned technical subset with explicit scope and comparison evidence. No audit, certification or full-framework compliance score.", nativeId: "iso-27001-2022", licenseNotice: "Independent mapping. Publisher requirement text and logos are not bundled. No affiliation or certification." },
  { id: "soc2", name: "SOC 2", publisher: "AICPA", kind: "Control framework", source: "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022", description: "Independent Intune configuration comparisons for selected technical requirements.", coverage: "Versioned technical subset with explicit scope and comparison evidence. No audit, certification or full-framework compliance score.", nativeId: "soc2-tsc", licenseNotice: "Independent mapping. Publisher requirement text and logos are not bundled. No affiliation or certification." },
  { id: "def-stan", name: "UK MOD Def Stan 05-138", publisher: "UK Ministry of Defence", kind: "Control framework", source: "https://www.gov.uk/government/publications/cyber-security-for-defence-suppliers-def-stan-05-138-issue-4", description: "Independent Intune configuration comparisons for selected technical requirements.", coverage: "Versioned technical subset with explicit scope and comparison evidence. No audit, certification or full-framework compliance score.", nativeId: "def-stan-05-138-i4", licenseNotice: "Independent mapping. Publisher requirement text and logos are not bundled. No affiliation or certification." },
  { id: "cyber-essentials", name: "Cyber Essentials", publisher: "NCSC", kind: "Control framework", source: "https://www.ncsc.gov.uk/cyberessentials/overview", description: "Independent Intune configuration comparisons for selected technical requirements.", coverage: "Versioned technical subset with explicit scope and comparison evidence. No audit, certification or full-framework compliance score.", nativeId: "cyber-essentials-v3", licenseNotice: "Contains public sector information from NCSC licensed under the Open Government Licence v3.0. No endorsement or certification." },
  { id: "custom", name: "Custom Baselines", publisher: "Your organization", kind: "Custom", source: "", description: "Your own approved policy standard or customer-specific baseline.", coverage: "Import Settings Catalog policy JSON and provide a version or reference. Packs and assessment history are saved in protected local storage." },
]

export function searchFrameworks(query: string): Framework[] {
  const terms = query.trim().toLowerCase().split(/\s+/)
  return frameworks.filter(f => terms.every(term => `${f.name} ${f.publisher} ${f.kind} ${f.description}`.toLowerCase().includes(term)))
}
