/** Printable reports (PDF through the main process) and CSV exports, built from plain text only. */

export interface ReportSection {
  heading: string
  note?: string
  columns: string[]
  rows: string[][]
}

export interface Report {
  title: string
  subtitle?: string
  meta: Array<[string, string]>
  summary?: Array<[string, string]>
  sections: ReportSection[]
  footer?: string
}

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!)
}

const STYLE = `
  @page { size: A4; margin: 16mm 14mm; }
  body { font-family: "Segoe UI", -apple-system, Helvetica, Arial, sans-serif; color: #161514; font-size: 10.5px; line-height: 1.45; }
  h1 { font-size: 22px; font-weight: 600; margin: 0 0 4px; }
  h2 { font-size: 14px; font-weight: 600; margin: 22px 0 6px; page-break-after: avoid; }
  .subtitle { color: #57534e; margin: 0 0 14px; font-size: 12px; }
  .meta { display: grid; grid-template-columns: max-content 1fr; gap: 2px 14px; margin-bottom: 14px; }
  .meta dt { color: #78716c; } .meta dd { margin: 0; }
  .summary { display: flex; flex-wrap: wrap; gap: 8px; margin: 12px 0; }
  .summary div { border: 1px solid #e7e5e4; border-radius: 10px; padding: 8px 12px; min-width: 90px; }
  .summary strong { display: block; font-size: 16px; }
  .note { color: #57534e; margin: 0 0 6px; }
  table { width: 100%; border-collapse: collapse; table-layout: fixed; }
  th, td { text-align: left; vertical-align: top; padding: 4px 6px; border-bottom: 1px solid #e7e5e4; word-wrap: break-word; overflow-wrap: anywhere; white-space: pre-line; }
  th { background: #f5f5f4; font-weight: 600; }
  tr { page-break-inside: avoid; }
  .empty { color: #78716c; font-style: italic; }
  footer { margin-top: 24px; color: #78716c; font-size: 9px; }
`

/** A standalone HTML document with no scripts or external resources. */
export function reportHtml(report: Report): string {
  const e = escapeHtml
  const table = (section: ReportSection) => section.rows.length
    ? `<table><thead><tr>${section.columns.map((c) => `<th>${e(c)}</th>`).join("")}</tr></thead><tbody>${section.rows.map((row) => `<tr>${row.map((cell) => `<td>${e(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`
    : `<p class="empty">Nothing to report.</p>`
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>${e(report.title)}</title><style>${STYLE}</style></head><body>
<h1>${e(report.title)}</h1>${report.subtitle ? `<p class="subtitle">${e(report.subtitle)}</p>` : ""}
<dl class="meta">${report.meta.map(([k, v]) => `<dt>${e(k)}</dt><dd>${e(v)}</dd>`).join("")}</dl>
${report.summary ? `<div class="summary">${report.summary.map(([k, v]) => `<div><strong>${e(v)}</strong>${e(k)}</div>`).join("")}</div>` : ""}
${report.sections.map((s) => `<h2>${e(s.heading)}</h2>${s.note ? `<p class="note">${e(s.note)}</p>` : ""}${table(s)}`).join("\n")}
<footer>${e(report.footer ?? `Generated by TenuVault on ${new Date().toLocaleString()}.`)}</footer></body></html>`
}

/** CSV with every cell quoted; cells that a spreadsheet would run as a formula are prefixed with '. */
export function toCsv(rows: string[][]): string {
  const cell = (value: string) => {
    const safe = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value
    return `"${safe.replace(/"/g, '""')}"`
  }
  return rows.map((row) => row.map(cell).join(",")).join("\r\n")
}
