import type { FrameworkDefinition } from "../types";

// References to the BSI framework do not grant republication rights. The German Federal
// Office for Information Security. The client Bausteine SYS.2.2.3, SYS.2.4,
// SYS.3.2.1 and SYS.3.2.2 are mapped at requirement level, verified against
// the Edition 2023 Baustein texts; only requirements with technical Intune
// evidence are listed (organizational requirements such as SYS.3.2.2.A1 are
// out of scope for a tenant export). The remaining Bausteine are mapped at
// Baustein level until their requirement-level mappings are verified the same
// way.
export const BSI_IT_GRUNDSCHUTZ: FrameworkDefinition = {
  id: "bsi-it-grundschutz",
  name: "BSI IT-Grundschutz",
  version: "Kompendium Edition 2023",
  note: "Client Bausteine (SYS.2.2.3, SYS.2.4, SYS.3.2.1, SYS.3.2.2) are mapped at requirement level; other Bausteine at building-block level. Only requirements with technical device-management evidence are listed. Organizational requirements must be assessed separately.",
  source: {
    url: "https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Grundschutz/IT-GS-Kompendium/IT_Grundschutz_Kompendium_Edition2023.pdf?__blob=publicationFile&v=4",
    verifiedAt: "2026-09-04",
  },
  controls: {
    "CON.1": {
      id: "CON.1",
      evidenceStrength: "supporting",
      granularity: "buildingBlock",
      title: "Endpoint evidence mapping CON.1",
      summary: "TenuVault compares selected disk encryption, storage encryption settings for this reference. Check selection and expected values are our interpretation.",
    },
    "OPS.1.1.3": {
      id: "OPS.1.1.3",
      evidenceStrength: "supporting",
      granularity: "buildingBlock",
      title: "Endpoint evidence mapping OPS.1.1.3",
      summary: "TenuVault compares selected quality update deadline, automatic updates, minimum os version settings for this reference. Check selection and expected values are our interpretation.",
    },
    "OPS.1.1.4": {
      id: "OPS.1.1.4",
      evidenceStrength: "supporting",
      granularity: "buildingBlock",
      title: "Endpoint evidence mapping OPS.1.1.4",
      summary: "TenuVault compares selected office macro antivirus, antivirus required, periodic antimalware scan, behavior monitoring, realtime antimalware settings for this reference. Check selection and expected values are our interpretation.",
    },
    "ORP.4": {
      id: "ORP.4",
      evidenceStrength: "supporting",
      granularity: "buildingBlock",
      title: "Endpoint evidence mapping ORP.4",
      summary: "TenuVault compares selected laps management, password required, passcode required settings for this reference. Check selection and expected values are our interpretation.",
    },
    "NET.3.2": {
      id: "NET.3.2",
      evidenceStrength: "supporting",
      granularity: "buildingBlock",
      title: "Endpoint evidence mapping NET.3.2",
      summary: "TenuVault compares selected firewall settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.1": {
      id: "SYS.2.1",
      evidenceStrength: "supporting",
      granularity: "buildingBlock",
      title: "Endpoint evidence mapping SYS.2.1",
      summary: "TenuVault compares selected laps management, applocker rule collections, office macros disabled, office internet macros blocked, office signed macros settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.2.3.A4": {
      id: "SYS.2.2.3.A4",
      evidenceStrength: "direct",
      granularity: "requirement",
      platforms: ["windows"],
      title: "Endpoint evidence mapping SYS.2.2.3.A4",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected telemetry minimized settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.2.3.A5": {
      id: "SYS.2.2.3.A5",
      evidenceStrength: "supporting",
      granularity: "requirement",
      platforms: ["windows"],
      title: "Endpoint evidence mapping SYS.2.2.3.A5",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected office macro antivirus, antivirus required, realtime antimalware settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.2.3.A6": {
      id: "SYS.2.2.3.A6",
      evidenceStrength: "supporting",
      granularity: "requirement",
      platforms: ["windows"],
      title: "Endpoint evidence mapping SYS.2.2.3.A6",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected microsoft account blocked settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.2.3.A14": {
      id: "SYS.2.2.3.A14",
      evidenceStrength: "direct",
      granularity: "requirement",
      platforms: ["windows"],
      title: "Endpoint evidence mapping SYS.2.2.3.A14",
      tier: "Standard-Anforderung",
      summary: "TenuVault compares selected cortana disabled settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.2.3.A23": {
      id: "SYS.2.2.3.A23",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "LSA protected-mode monitoring and applicable RDP restrictions are unassessed.",
      ],
      granularity: "requirement",
      platforms: ["windows"],
      title: "Endpoint evidence mapping SYS.2.2.3.A23",
      tier: "Anforderung bei erhöhtem Schutzbedarf",
      summary: "TenuVault compares selected lsa protection, remote credential guard, credential guard, secure boot, code integrity settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.4.A2": {
      id: "SYS.2.4.A2",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "XProtect status, installed software and actual activation of macOS protections are unassessed.",
      ],
      granularity: "requirement",
      platforms: ["macos"],
      title: "Endpoint evidence mapping SYS.2.4.A2",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected system integrity, gatekeeper settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.4.A4": {
      id: "SYS.2.4.A4",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "FileVault recovery key custody and storage location are unassessed.",
      ],
      granularity: "requirement",
      platforms: ["macos"],
      title: "Endpoint evidence mapping SYS.2.4.A4",
      tier: "Standard-Anforderung",
      summary: "TenuVault compares selected disk encryption settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.4.A6": {
      id: "SYS.2.4.A6",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "Hardware support and installed OS security-update support are not verified. A configured minimum version does not establish currency.",
      ],
      granularity: "requirement",
      platforms: ["macos"],
      title: "Endpoint evidence mapping SYS.2.4.A6",
      tier: "Standard-Anforderung",
      summary: "TenuVault compares selected minimum os version settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.2.4.A10": {
      id: "SYS.2.4.A10",
      evidenceStrength: "supporting",
      granularity: "requirement",
      platforms: ["macos"],
      title: "Endpoint evidence mapping SYS.2.4.A10",
      tier: "Standard-Anforderung",
      summary: "TenuVault compares selected firewall settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.1.A4": {
      id: "SYS.3.2.1.A4",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "Passcode complexity, lock timeout and effective device enforcement require separate review.",
      ],
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.1.A4",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected passcode required, password required settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.1.A5": {
      id: "SYS.3.2.1.A5",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "Installed OS and app support, actual patch installation and replacement of unsupported devices are unassessed.",
      ],
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.1.A5",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected minimum os version settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.1.A8": {
      id: "SYS.3.2.1.A8",
      evidenceStrength: "supporting",
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.1.A8",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected app source restriction settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.1.A11": {
      id: "SYS.3.2.1.A11",
      evidenceStrength: "supporting",
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.1.A11",
      tier: "Standard-Anforderung",
      summary: "TenuVault compares selected storage encryption settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.2.A2": {
      id: "SYS.3.2.2.A2",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "Approved device models and organizational authorization are unassessed.",
      ],
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.2.A2",
      tier: "Basis-Anforderung",
      summary: "TenuVault compares selected minimum os version settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.2.A17": {
      id: "SYS.3.2.2.A17",
      evidenceStrength: "supporting",
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.2.A17",
      tier: "Anforderung bei erhöhtem Schutzbedarf",
      summary: "TenuVault compares selected jailbreak block, device integrity settings for this reference. Check selection and expected values are our interpretation.",
    },
    "SYS.3.2.2.A23": {
      id: "SYS.3.2.2.A23",
      evidenceStrength: "supporting",
      unassessedAspects: [
        "Alerts, wipe and lock actions, grace periods and effective Conditional Access coverage require separate review.",
      ],
      granularity: "requirement",
      platforms: ["ios", "android"],
      title: "Endpoint evidence mapping SYS.3.2.2.A23",
      tier: "Anforderung bei erhöhtem Schutzbedarf",
      summary: "TenuVault compares selected compliant device required, jailbreak block, device integrity settings for this reference. Check selection and expected values are our interpretation.",
    },
  },
  mappings: {
    "windows-lsa-protection": ["SYS.2.2.3.A23"],
    "windows-remote-credential-guard": ["SYS.2.2.3.A23"],
    "windows-laps-management": ["ORP.4", "SYS.2.1"],
    "windows-process-creation-logging": [],
    "windows-powershell-module-logging": [],

    "windows-applocker-rule-collections": ["SYS.2.1"],
    "windows-office-v3-signatures": [],
    "windows-office-macros-disabled": ["SYS.2.1"],
    "windows-office-internet-macros-blocked": ["SYS.2.1"],
    "windows-office-macro-antivirus": ["OPS.1.1.4", "SYS.2.2.3.A5"],
    "windows-office-signed-macros": ["SYS.2.1"],
    "macos-office-macros-disabled": ["SYS.2.1"],
    "windows-office-macro-settings-managed": ["SYS.2.1"],
    "windows-ie-disabled": ["SYS.2.1"],
    "windows-browser-java-blocked": ["SYS.2.1"],
    "windows-browser-intrusive-ads-blocked": ["SYS.2.1"],
    "macos-browser-intrusive-ads-blocked": ["SYS.2.1"],
    "windows-browser-security-settings-managed": ["SYS.2.1"],
    "tenant-mfa-all-apps": [],
    "tenant-phishing-resistant-mfa": [],
    "windows-powershell-scriptblock-logging": [],
    "windows-powershell-transcription": [],

    "windows-office-macro-win32-block": [],
    "windows-office-child-process-block": [],
    "windows-office-executable-block": [],
    "windows-office-injection-block": [],
    "windows-adobe-child-process-block": [],

    "windows-network-inspection": [],
    "windows-virtualization-security": [],
    "windows-credential-theft-protection": [],
    "tenant-mfa-required": [],
    "ios-app-data-transfer": [],
    "android-app-data-transfer": [],

    "windows-antivirus-required": ["OPS.1.1.4", "SYS.2.2.3.A5"],
    "windows-periodic-antimalware-scan": ["OPS.1.1.4"],
    "windows-quality-update-deadline": ["OPS.1.1.3"],
    "windows-application-control": ["SYS.2.1"],
    "windows-behavior-monitoring": ["OPS.1.1.4"],
    "windows-memory-integrity": ["SYS.2.1"],
    "windows-credential-guard": ["SYS.2.2.3.A23"],
    "tenant-compliant-device-required": ["SYS.3.2.2.A23"],

    "windows-disk-encryption": ["CON.1", "SYS.2.1"],
    "macos-disk-encryption": ["CON.1", "SYS.2.4.A4"],
    "android-storage-encryption": ["CON.1", "SYS.3.2.1.A11"],
    "windows-realtime-antimalware": ["OPS.1.1.4", "SYS.2.2.3.A5"],
    "windows-telemetry-minimized": ["SYS.2.2.3.A4"],
    "windows-cortana-disabled": ["SYS.2.2.3.A14"],
    "windows-microsoft-account-blocked": ["SYS.2.2.3.A6"],
    "windows-firewall": ["NET.3.2", "SYS.2.1"],
    "macos-firewall": ["NET.3.2", "SYS.2.4.A10"],
    "windows-password-required": ["ORP.4", "SYS.2.1"],
    "macos-password-required": ["ORP.4", "SYS.2.1"],
    "ios-passcode-required": ["ORP.4", "SYS.3.2.1.A4"],
    "android-password-required": ["ORP.4", "SYS.3.2.1.A4"],
    "windows-automatic-updates": ["OPS.1.1.3", "SYS.2.1"],
    "windows-minimum-os-version": ["OPS.1.1.3"],
    "macos-minimum-os-version": ["OPS.1.1.3", "SYS.2.4.A6"],
    "ios-minimum-os-version": ["OPS.1.1.3", "SYS.3.2.1.A5", "SYS.3.2.2.A2"],
    "android-minimum-os-version": ["OPS.1.1.3", "SYS.3.2.1.A5", "SYS.3.2.2.A2"],
    "android-app-source-restriction": ["SYS.3.2.1.A8"],
    "windows-secure-boot": ["SYS.2.2.3.A23"],
    "windows-code-integrity": ["SYS.2.2.3.A23"],
    "macos-system-integrity": ["SYS.2.4.A2"],
    "macos-gatekeeper": ["SYS.2.4.A2"],
    "ios-jailbreak-block": ["SYS.3.2.2.A17", "SYS.3.2.2.A23"],
    "android-device-integrity": ["SYS.3.2.2.A17", "SYS.3.2.2.A23"],
  },
};
