import type { FrameworkDefinition } from "../types";

// ISO/IEC 27001 is referenced by control number only. Titles and summaries are
// original descriptions written for this device-management evidence mapping.
export const ISO_27001: FrameworkDefinition = {
  id: "iso-27001-2022",
  name: "ISO/IEC 27001:2022",
  version: "2022, Annex A",
  note: "Device-management evidence for selected technological (Annex A clause 8) controls, referenced by control number with original summaries. Organizational, people, and physical controls are out of scope for an Intune tenant export.",
  source: {
    url: "https://www.iso.org/standard/27001",
    verifiedAt: "2026-09-04",
  },
  controls: {
    "8.1": {
      id: "8.1",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.1",
      summary: "TenuVault compares selected compliant device required, app data transfer, disk encryption, storage encryption settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.5": {
      id: "8.5",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.5",
      summary: "TenuVault compares selected lsa protection, remote credential guard, laps management, mfa all apps, phishing resistant mfa, credential guard settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.7": {
      id: "8.7",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.7",
      summary: "TenuVault compares selected office macro antivirus, antivirus required, periodic antimalware scan, behavior monitoring, network inspection, realtime antimalware settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.8": {
      id: "8.8",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.8",
      summary: "TenuVault compares selected quality update deadline, automatic updates, minimum os version settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.9": {
      id: "8.9",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.9",
      summary: "TenuVault compares selected office macros disabled, office internet macros blocked, office signed macros, office macro settings managed, ie disabled settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.19": {
      id: "8.19",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.19",
      summary: "TenuVault compares selected applocker rule collections, application control, gatekeeper, app source restriction settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.20": {
      id: "8.20",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.20",
      summary: "TenuVault compares selected firewall settings for this reference. Check selection and expected values are our interpretation.",
    },
    "8.24": {
      id: "8.24",
      evidenceStrength: "supporting",
      granularity: "requirement",
      title: "Endpoint evidence mapping 8.24",
      summary: "TenuVault compares selected disk encryption, storage encryption settings for this reference. Check selection and expected values are our interpretation.",
    },
  },
  mappings: {
    "windows-lsa-protection": ["8.5"],
    "windows-remote-credential-guard": ["8.5"],
    "windows-laps-management": ["8.5"],
    "windows-process-creation-logging": [],
    "windows-powershell-module-logging": [],

    "windows-applocker-rule-collections": ["8.19"],
    "windows-office-v3-signatures": [],
    "windows-office-macros-disabled": ["8.9"],
    "windows-office-internet-macros-blocked": ["8.9"],
    "windows-office-macro-antivirus": ["8.7"],
    "windows-office-signed-macros": ["8.9"],
    "macos-office-macros-disabled": ["8.9"],
    "windows-office-macro-settings-managed": ["8.9"],
    "windows-ie-disabled": ["8.9"],
    "windows-browser-java-blocked": ["8.9"],
    "windows-browser-intrusive-ads-blocked": ["8.9"],
    "macos-browser-intrusive-ads-blocked": ["8.9"],
    "windows-browser-security-settings-managed": ["8.9"],
    "tenant-mfa-all-apps": ["8.5"],
    "tenant-phishing-resistant-mfa": ["8.5"],
    "windows-powershell-scriptblock-logging": [],
    "windows-powershell-transcription": [],

    "windows-office-macro-win32-block": [],
    "windows-office-child-process-block": [],
    "windows-office-executable-block": [],
    "windows-office-injection-block": [],
    "windows-adobe-child-process-block": [],

    "windows-virtualization-security": [],
    "windows-credential-theft-protection": [],

    "windows-antivirus-required": ["8.7"],
    "windows-periodic-antimalware-scan": ["8.7"],
    "windows-quality-update-deadline": ["8.8"],
    "windows-application-control": ["8.19"],
    "windows-behavior-monitoring": ["8.7"],
    "windows-network-inspection": ["8.7"],
    "windows-memory-integrity": ["8.9"],
    "windows-credential-guard": ["8.5"],
    "tenant-mfa-required": ["8.5"],
    "tenant-compliant-device-required": ["8.1"],
    "ios-app-data-transfer": ["8.1"],
    "android-app-data-transfer": ["8.1"],

    "windows-disk-encryption": ["8.1", "8.24"],
    "macos-disk-encryption": ["8.1", "8.24"],
    "android-storage-encryption": ["8.1", "8.24"],
    "windows-realtime-antimalware": ["8.7"],
    "windows-firewall": ["8.20"],
    "macos-firewall": ["8.20"],
    "windows-password-required": ["8.5"],
    "macos-password-required": ["8.5"],
    "ios-passcode-required": ["8.5"],
    "android-password-required": ["8.5"],
    "windows-automatic-updates": ["8.8"],
    "windows-minimum-os-version": ["8.8"],
    "macos-minimum-os-version": ["8.8"],
    "ios-minimum-os-version": ["8.8"],
    "android-minimum-os-version": ["8.8"],
    "windows-secure-boot": ["8.9"],
    "windows-code-integrity": ["8.9"],
    "macos-system-integrity": ["8.9"],
    "windows-telemetry-minimized": ["8.9"],
    "windows-cortana-disabled": ["8.9"],
    "windows-microsoft-account-blocked": ["8.9"],
    "ios-jailbreak-block": ["8.1", "8.9"],
    "android-device-integrity": ["8.1", "8.9"],
    "macos-gatekeeper": ["8.19"],
    "android-app-source-restriction": ["8.19"],
  },
};
